version: '3.5'
services:
  database:
    container_name: db2
    image: postgres:12.7-alpine
    env_file: database.conf
    ports:
      - 5432:5432
    volumes:
      - db_volume:/var/lib/postgresql

volumes:
  db_volume: